version: '2'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  node:
    build: ./Node
    depends_on:
      - mongo
    links:
      - "mongo"
    ports:
      - "3001:3001"
  haproxy:
    build: ./HAProxy
    depends_on:
      - node
    links:
      - "node"
    ports:
    - "80:80"
